-- AlterEnum
ALTER TYPE "PRODUCT_TAG" ADD VALUE IF NOT EXISTS 'laptop';
ALTER TYPE "PRODUCT_TAG" ADD VALUE IF NOT EXISTS 'smartphone';
ALTER TYPE "PRODUCT_TAG" ADD VALUE IF NOT EXISTS 'home_appliance';
ALTER TYPE "PRODUCT_TAG" ADD VALUE IF NOT EXISTS 'furniture';
ALTER TYPE "PRODUCT_TAG" ADD VALUE IF NOT EXISTS 'fitness';
ALTER TYPE "PRODUCT_TAG" ADD VALUE IF NOT EXISTS 'books';
